version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  sentry-test:
    build:
      context: ../..
      dockerfile: docker/redis/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ../../:/app
    working_dir: /app
    command: lua docker/redis/test.lua