# StyLua configuration file

column_width = 200
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"

# Collapse simple structures to single line if they fit
collapse_simple_statement = "Always"

[sort_requires]
enabled = false