permissions:
  contents: read
name: Love2D Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  love2d-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    
    - name: Setup Lua 5.4
      uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10
      with:
        luaVersion: "5.4"
    
    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4
    
    - name: Install SSL dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev
    
    - name: Install SSL dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl
        echo "OPENSSL_DIR=$(brew --prefix openssl)" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: make install
    
    - name: Install Love2D and run tests
      run: make ci-love2d
    
    - name: Test example module loading
      run: |
        cd examples/love2d
        LUA_PATH="../../build/?.lua;../../build/?/init.lua;;" lua test_modules.lua
    
    - name: Package Love2D example
      run: |
        cd examples/love2d
        zip -r sentry-love2d-demo.love . -x "*.DS_Store" "test_modules.lua"
        ls -la sentry-love2d-demo.love
        
    - name: Upload Love2D artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: love2d-artifacts-${{ matrix.os }}
        path: |
          examples/love2d/sentry-love2d-demo.love
        retention-days: 7