permissions:
  contents: read
name: Tests

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    paths-ignore:
      - "**.md"

env:
  LUAJIT_2_0_VERSION: "v2.0.5"
  LUAJIT_2_1_VERSION: "v2.1.0-beta3"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        lua-version: ["5.1", "5.2", "5.3", "5.4", "luajit-2.0", "luajit-2.1"]
        include:
          - lua-version: "luajit-2.0" 
            luajit-version: "v2.0.5"
            luajit-label: "LuaJIT 2.0.5"
          - lua-version: "luajit-2.1"
            luajit-version: "v2.1.0-beta3"  
            luajit-label: "LuaJIT 2.1.0-beta3"
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    
    - name: Setup Lua (standard versions)
      if: ${{ !contains(matrix.lua-version, 'luajit') }}
      uses: leafo/gh-actions-lua@35bcb06abec04ec87df82e08caa84d545348536e # v10
      with:
        luaVersion: ${{ matrix.lua-version }}
    
    - name: Setup ${{ matrix.luajit-label || 'LuaJIT' }} on Ubuntu (via apt)
      if: contains(matrix.lua-version, 'luajit') && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y luajit libluajit-5.1-dev
        # Create compatibility symlinks
        sudo ln -sf $(which luajit) /usr/local/bin/lua
        echo "LUA_DIR=/usr" >> $GITHUB_ENV
        echo "LUA_INCDIR=/usr/include/luajit-2.1" >> $GITHUB_ENV
    
    - name: Setup ${{ matrix.luajit-label || 'LuaJIT' }} on macOS (via Homebrew)
      if: contains(matrix.lua-version, 'luajit') && matrix.os == 'macos-latest'
      run: |
        brew install luajit
        # Create symlinks for compatibility
        sudo ln -sf $(which luajit) /usr/local/bin/lua
        echo "$(dirname $(which luajit))" >> $GITHUB_PATH
        echo "LUA_DIR=$(brew --prefix luajit)" >> $GITHUB_ENV
        echo "LUA_INCDIR=$(brew --prefix luajit)/include/luajit-2.1" >> $GITHUB_ENV
    
    - name: Setup LuaRocks
      if: ${{ !contains(matrix.lua-version, 'luajit') }}
      uses: leafo/gh-actions-luarocks@e65774a6386cb4f24e293dca7fc4ff89165b64c5 # v4
    
    - name: Setup LuaRocks for ${{ matrix.luajit-label || 'LuaJIT' }} on Ubuntu
      if: contains(matrix.lua-version, 'luajit') && matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y luarocks
        # Create user config directory
        mkdir -p ~/.luarocks
        # Configure luarocks to work with luajit using --local for all operations
        luarocks config --local lua_interpreter luajit
        luarocks config --local variables.LUA_DIR /usr
        luarocks config --local variables.LUA_INCDIR /usr/include/luajit-2.1
        # Override make install to use --local flag
        echo 'LUAROCKS_FLAGS=--local' >> $GITHUB_ENV
    
    - name: Setup LuaRocks for ${{ matrix.luajit-label || 'LuaJIT' }} on macOS
      if: contains(matrix.lua-version, 'luajit') && matrix.os == 'macos-latest'
      run: |
        brew install luarocks
        # Configure luarocks to work with luajit
        luarocks config lua_interpreter luajit
        luarocks config variables.LUA_DIR $(brew --prefix luajit)
        luarocks config variables.LUA_INCDIR $(brew --prefix luajit)/include/luajit-2.1
    
    - name: Install SSL dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev
    
    - name: Install SSL dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl
        echo "OPENSSL_DIR=$(brew --prefix openssl)" >> $GITHUB_ENV
    
    
    - name: Install dependencies
      shell: bash
      run: |
        # For Ubuntu LuaJIT, use --local flag to avoid permission issues
        if [ "${{ matrix.os }}" = "ubuntu-latest" ] && [[ "${{ matrix.lua-version }}" == *"luajit"* ]]; then
          echo "Installing dependencies locally for Ubuntu LuaJIT..."
          luarocks install --local busted
          luarocks install --local tl
          luarocks install --local lua-cjson
          luarocks install --local luasocket
          if [ -n "$OPENSSL_DIR" ]; then
            echo "Installing luasec with OPENSSL_DIR=$OPENSSL_DIR"
            luarocks install --local luasec OPENSSL_DIR=$OPENSSL_DIR
          else
            luarocks install --local luasec
          fi
          luarocks install --local luacov
          luarocks install --local luacov-reporter-lcov
          # Add local luarocks bin to PATH
          echo "$HOME/.luarocks/bin" >> $GITHUB_PATH
        else
          make install
        fi
    
    - name: Build project
      run: make build
    
    - name: Run tests with coverage
      run: make coverage-report
    
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: coverage-${{ matrix.os }}-lua${{ matrix.lua-version }}
        path: |
          coverage.info
          luacov.report.out
          test-results.xml
        retention-days: 7
    
    - name: Upload coverage to Codecov (Ubuntu Lua 5.4 only)
      if: matrix.os == 'ubuntu-latest' && matrix.lua-version == '5.4'
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
      with:
        file: ./coverage.info
        flags: unittests
        name: codecov-${{ matrix.lua-version }}
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Upload test results to Codecov (Ubuntu Lua 5.4 only)
      if: matrix.os == 'ubuntu-latest' && matrix.lua-version == '5.4'
      uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1
      with:
        file: ./test-results.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: |
          README.md
          .github/example-event.png
          CHANGELOG.md
          *.rockspec
          roblox.json
          build/*
          examples/*